# Configure the English version of the site
[en]
  languageCode = "en-us"
  contentDir = "content/en"
  title = "Kmesh"
  [en.params]
    description = "Your description here"
  
  # English Menu (To match the Chinese version)
  [[en.menu.main]]
    name = "Docs"
    url = "docs/"
    weight = 20
  [[en.menu.main]]
    name = "Blog"
    url = "blog/"
    weight = 30
  [[en.menu.main]]
    name = "Download"
    url = "https://github.com/kmesh-net/kmesh/releases"
    weight = 40

  # English Social Links
  [[en.menu.main_right]]
    name = "<i class=\"fab fa-github\"></i>"
    url = "https://github.com/kmesh-net/kmesh"
    weight = 10

  [[en.menu.main_right]]
    name = "<i class=\"fab fa-x-twitter\"></i>"
    url = "https://twitter.com/Kmesh_net"
    weight = 20

  [[en.menu.main_right]]
    name = "<i class=\"fab fa-weixin\"></i>"
    url = "https://blog.51cto.com/u_15127420/4992806"
    weight = 40

  # English Documentation
  [[en.menu.docs]]
    name = "Welcome"
    weight = 5
    identifier = "welcome"

  [[en.menu.docs]]
    name = "Architecture"
    weight = 10
    identifier = "architecture"

  [[en.menu.docs]]
    name = "Quickstart"
    weight = 15
    identifier = "quickstart"

  [[en.menu.docs]]
    name = "Performance"
    weight = 20
    identifier = "performance"

  [[en.menu.docs]]
    name = "Developer Guide"
    weight = 25
    identifier = "developer guide"

  [[en.menu.docs]]
    name = "Community"
    weight = 30
    identifier = "community"

# Configure the Chinese version of the site
[zh]
  languageCode = "zh-Hans"
  contentDir = "content/zh"
  title = "Kmesh"
  [zh.params]
    description = ""

  [[zh.menu.main]]
    name = "文档"
    url = "docs/"
    weight = 20
  [[zh.menu.main]]
    name = "博客"
    url = "blog/"
    weight = 30
  [[zh.menu.main]]
    name = "下载"
    url = "https://github.com/kmesh-net/kmesh/releases"
    weight = 40

  # Chinese Social Links
  [[zh.menu.main_right]]
    name = "<i class=\"fab fa-github\"></i>"
    url = "https://github.com/kmesh-net/kmesh"
    weight = 10

  [[zh.menu.main_right]]
    name = "<i class=\"fab fa-x-twitter\"></i>"
    url = "https://twitter.com/Kmesh_net"
    weight = 20

  [[zh.menu.main_right]]
    name = "<i class=\"fab fa-weixin\"></i>"
    url = "https://blog.51cto.com/u_15127420/4992806"
    weight = 40

  # Chinese Documentation
  [[zh.menu.docs]]
    name = "欢迎入门"
    weight = 5
    identifier = "welcome"

  [[zh.menu.docs]]
    name = "系统架构"
    weight = 10
    identifier = "architecture"

  [[zh.menu.docs]]
    name = "快速开始"
    weight = 15
    identifier = "quickstart"

  [[zh.menu.docs]]
    name = "性能"
    weight = 20
    identifier = "performance"

  [[zh.menu.docs]]
    name = "开发指南"
    weight = 25
    identifier = "developer guide"

  [[zh.menu.docs]]
    name = "社区"
    weight = 30
    identifier = "community"
